development:
  adapter: postgresql
  encoding: unicode
  database: invite-customers-app_development
  pool: 5
  username:
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: invite-customers-app_test
  pool: 5
  username:
  password:
  timeout: 5000
